### PR TITLE
feat: add mysqltest compatibility layer

### PR DESCRIPTION
**Pull request by sqin2019**
Mostly copied from https://github.com/abcxyz/pkg/pull/109/files#diff-f72aa91018029b43c12c7461bc4b68dfdd597e7be83fbfb93d96a136e9272c15

### CODE REVIEW

**Comment by drevell** [comment]
I didn't review this too closely, because it's mostly copied.

**Comment by pdewilde** [comment]
I think @sethvargo intentionally removed this, as it wasn't really being used.

@sqin2019 I know there is one usage you are working to replace, but might it be easier to just change that one usage?

**Comment by sethvargo** [comment]
I didn't think anyone was using this. Is there a reason we need it?

**Comment by sethvargo** [comment]
Great thanks - let me know how I can help!

**Pull request closed without merging**
